### PR TITLE
added Compat package and fixes #42

### LINKED ISSUE #42: Package fails to load on latest Julia v0.4
````julia

julia> versioninfo()
Julia Version 0.4.0-dev+4319
Commit ef06211* (2015-04-17 03:26 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.0

julia> using Reactive
WARNING: uint(x) is deprecated, use UInt(x) instead.
 in depwarn at ./deprecated.jl:40
 in uint at no file
 in anonymous at no file
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:52
ERROR: LoadError: MethodError: `start` has no method matching start(::Type{Reactive.Signal{T}})
 in append_any at no file
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:52
while loading /Users/Administrator/.julia/v0.4/Reactive/src/Reactive.jl, in expression starting on line 63
````

### PR DESCRIPTION
**Pull request by milktrader**

### CODE REVIEW

**Comment by shashi** [comment]
Thank you! :D

**Comment by milktrader** [comment]
Travis failed on this, btw, not sure it's related to this PR  but don't think so:

````bash
ERROR: LoadError: LoadError: MethodError: `*` has no method matching *(::Reactive.Lift{Int64}, ::Reactive.Lift{Int64})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any)
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
 in power_by_squaring at intfuncs.jl:76
 in ^ at intfuncs.jl:106
 in anonymous at no file
 in anonymous at /home/travis/.julia/v0.4/Reactive/src/macros.jl:68
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at loading.jl:129
 in process_options at ./client.jl:305
 in _start at ./client.jl:389
while loading /home/travis/build/JuliaLang/Reactive.jl/tests/macro.jl, in expression starting on line 15
while loading /home/travis/build/JuliaLang/Reactive.jl/tests/test.jl, in expression starting on line 4
The command "julia ./tests/test.jl" exited with 1.
````

**Comment by shashi** [comment]
Yes I know the tests break, and I don't think it's this PR that's causing it.

**Comment by shashi** [comment]
I've moved to FactCheck on `flatten` branch, working on getting this going now.

**Comment by milktrader** [comment]
Ok good. Yeah, I like FactCheck, good choice

**Pull request merged**
