### PR TITLE
better stop and start of event loop

### PR DESCRIPTION
**Pull request by SimonDanisch**
I changed the while loop to a for loop, since that seems to represent better what it is... Hope that's okay ;)

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Is throttle broken on 0.5, or is this just some fluctuation?
Removing `sleep` in `test/time.jl:93` seems to make the tests pass...

**Comment by shashi** [comment]
Weird how travis fails for all versions though...

**Comment by SimonDanisch** [comment]
Ah yeah on OSX... I just can't reproduce it locally ;)

**Comment by shashi** [comment]
looks like the increased compile time is causing the hand-wavy timing tests to fail.

**Pull request merged**
